### ISSUE TITLE
Spandx does not work on Windows 10 WSL2 - Debian install

### ISSUE THREAD

**Issue by kelsS** [redhataccess/spandx#280]
## Steps to reproduce
1. run WSL2 - Debian 11.4 on Windows 10
2. Clone [account team repo](https://gitlab.cee.redhat.com/customer-platform/account-team)
3. Run `npm install`
4. Run `npm start`
5. Navigate to the following url: https://qa.foo.redhat.com:1337/account-team-app 
6. You will see a "ERR_CONNECTION_CLOSED" screen
<img width="658" alt="spandx-error" src="https://user-images.githubusercontent.com/20908392/190684842-375dc351-2130-4d07-b1c5-e73f4700a2df.png">

## Local machine information
```
Brave browser - [Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit](https://brave.com/latest/)
Chrome browser - Version 105.0.5195.127 (Official Build) (64-bit)

Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	64.0 GB (63.8 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Version	21H2
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0
```

**Comment by kelsS** [comment]
This is a HuGE blocker for me. 😕 I cannot run any of the spandx apps locally to work on them. Any help is greatly appreciated!

**Comment by mwcz** [comment]
I have to confess to knowing nothing about WSL, so I'll ping you to set up a meeting and try to figure out how to debug this.

**Comment by mwcz** [comment]
The cause turned out to be <https://github.com/microsoft/WSL/issues/5969>, adding `::1` mappings to the hosts file fixed the issue.  I'll update the `spandx init cp addhosts` command to add ipv6 localhost IPs as well.

**Comment by mwcz** [comment]
#281 added ipv6 support to the `spandx init cp addhosts` command.

The easiest way to run it is: `npx spandx init cp addhosts`

(also, it removed the api.* hosts which aren't used anymore)
